package com.rs.net.decoders;

public class ClientOpcodes {

	public static final int REMOVE_LOGIN_BOX = 1,
			ERROR_CONNECTING_TO_SERVER = 2,//TODO
			INVALID_CREDIENTIALS = 3,
			ACCOUNT_DISABLED = 4,
			ACCOUNT_IN_SESSION = 5,
			SERVER_UPDATED = 6,
			WORD_FULL = 7,
			LOGIN_SERVER_OFFLINE = 8,
			LOGIN_LIMIT_EXCEEDED = 9,
			BAD_SESSION_ID = 10,
			COMMON_PASSWORD = 11,//TODO
			MEMBERS_ACCOUNT_F2P_WORLD = 12,
			COULD_NOT_COMPLETE_LOGIN = 13,
			SERVER_BEING_UPDATE = 14,
			WORLD_HOPPING = 15,
			TOO_MANY_LOGINS = 16,//TODO
			STANDING_IN_MEMBERS_AREA = 17,
			ACCOUNT_LOCKED = 18,
			FULL_SCREEN_IS_MEMBERS = 19,//TODO
			INVALID_LOGIN_SERVER = 20,
			ERROR_TRYING_CONNECT = 21,
			MALFORMED_LOGIN_PACKET = 22,
			NO_REPLY_FROM_LOGIN_SERVER = 23,//TODO
			ERROR_LOADING_PROFILE = 24,
			UNEXPECTED_LOGINSERVER_RESPONSE = 25,
			COMPUTER_ADDRESS_BLOCKED = 26,
			SERVICE_UNAVAILBLE = 27,
			NO_LOGINSERVER_RESPONSE_ANOTHER_WORLD = 28,
			ERROR_CONNECTING_TO_S = 29,//TODO
			NOT_MEMBERS_ACCOUNT = 30,
			CHANGE_DISPLAY_NAME_TO_LOGIN = 31,
			NEGATIVE_MEMBERSHIP = 32,
			UNEXPECTED_SERVER_RESPONSE = 33,
			NO_SERVER_RESPONSE = 34,
			SESSION_EXPIRED = 35,
			AUTHENTICATION_SERVER_OFFLINE = 36,
			ACCOUNT_INACCESSABLE = 37,
			WORLD_NO_LONGER_EXISTS = 39,
			INSTANCE_IS_FULL = 41,
			SYSTEMS_ARE_BUSY = 44,
			VALIDATE_EMAIL = 47,
			SESSION_NOW_ENDED = 48;


}
